# Generated by Django 5.2.1 on 2025-05-13 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Název')),
                ('release_date', models.DateField(verbose_name='Datum vydání')),
                ('developer', models.CharField(max_length=100, verbose_name='Vývojář')),
                ('publisher', models.CharField(max_length=100, verbose_name='Vydavatel')),
            ],
            options={
                'verbose_name': 'Hra',
                'verbose_name_plural': 'Hry',
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['username'], 'verbose_name': 'Uživatel', 'verbose_name_plural': 'Uživatelé'},
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Název')),
                ('games', models.ManyToManyField(related_name='genres', to='speedrun_app.game', verbose_name='Hry')),
            ],
            options={
                'verbose_name': 'Žánr',
                'verbose_name_plural': 'Žánry',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Speedrun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DurationField(verbose_name='Čas')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Datum')),
                ('platform', models.CharField(max_length=50, verbose_name='Platforma')),
                ('category', models.CharField(max_length=50, verbose_name='Kategorie')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speedruns', to='speedrun_app.game', verbose_name='Hra')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speedruns', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Speedrun',
                'verbose_name_plural': 'Speedruny',
                'ordering': ['time'],
            },
        ),
    ]
