# Generated by Django 5.2.1 on 2025-05-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun_app', '0002_game_alter_customuser_options_genre_speedrun'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='games',
        ),
        migrations.AddField(
            model_name='game',
            name='genres',
            field=models.ManyToManyField(related_name='games', to='speedrun_app.genre', verbose_name='Žánry'),
        ),
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis'),
        ),
    ]
