# Generated by Django 5.2.1 on 2025-05-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun_app', '0003_remove_genre_games_game_genres_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedrun',
            name='platform',
            field=models.CharField(choices=[('PC', 'PC'), ('PS4', 'PlayStation 4'), ('XBOX', 'Xbox One'), ('SWITCH', 'Nintendo Switch'), ('PS5', 'PlayStation 5'), ('XBOX_SERIES_X', 'Xbox Series X')], max_length=50, verbose_name='Platforma'),
        ),
    ]
