# Generated by Django 5.2.1 on 2025-05-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun_app', '0004_alter_speedrun_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis'),
        ),
    ]
