# Generated by Django 5.2.1 on 2025-05-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun_app', '0005_game_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Popis'),
        ),
    ]
