# Generated by Django 5.2.1 on 2025-05-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedrun_app', '0006_alter_game_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Speedrun',
            new_name='Run',
        ),
    ]
